### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by kailuowang**
also started to use sbt-release

### CODE REVIEW

**Comment by fdoumet** [comment]
Thanks for the update! Could you please update the readme accordingly?

**Comment by kailuowang** [comment]
I also added a travis.yml. Should be able to enable travis

**Comment by kailuowang** [comment]
@fdoumet mind to take another look?

**Comment by kailuowang** [comment]
Thanks!

**Comment by fdoumet** [comment]
Thanks for contributing!

**Pull request merged**
